/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "e2ap_v2_03.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ProtocolIE-ContainerList.h"

